move_to_initial_position:
  stiffness:
    translational: [800.0, 800.0, 800.0]
    rotational: [80.0, 80.0, 80.0]
  goal: [0.155, 0.3455, 0.050]

external_down_movement:
  stiffness:
    translational: [800.0, 800.0, 200.0]
    rotational: [80.0, 80.0, 80.0]
  goal: [0.155, 0.3455, -0.009]

spiral:
  stiffness:
    translational: [800.0, 800.0, 200.0]
    rotational: [80.0, 80.0, 80.0]
  goal: [0.155, 0.3455, -0.009]

wiggle:
  stiffness:
    translational: [800.0, 800.0, 200.0]
    rotational: [50.0, 50.0, 50.0]
  goal: [0.155, 0.3455, -0.009]
